name: Hello World

on:
  workflow_call:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout separate repo
        uses: actions/checkout@v2
        with:
          repository: vm-001/github-action-hello-world
      - run: |
          echo "Hello World!"
          cat README.md

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
