name: Hello World
description: ""
author: vm-001

runs:
  using: composite
  steps:
    - name: Checkout separate repo
      uses: actions/checkout@v2
      with:
        repository: vm-001/github-action-hello-world

    - shell: bash
      run: |
        echo "Hello World!"
        cat README.md

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
